## Genbank FASTA

```
>AC073210.8 Homo sapiens BAC clone RP11-460N20 from 7, complete sequence
GAATTCTTCAGGTAGCTTCCTAGGGTTTCCAAGGCAATACAAGAAGAATTTTGATAGGCAGGAAAATGCA...
```

## UNITE QIIME

```
SH099456.05FU_FJ357315_refs    k__Fungi;p__Ascomycota;c__Dothideomycetes;o__Pleosporales;f__Pleosporaceae;g__Embellisia;s__Embellisia_planifunda
```

## Greengenes

```
1111875	k__Bacteria; p__Proteobacteria; c__Betaproteobacteria; o__Burkholderiales; f__Comamonadaceae; g__Limnohabitans; s__
```

## RDP 

```
>S000448483 Sparassis crispa; MBUH-PIRJO&ILKKA94-1587/ss5	Lineage=Root;rootrank;Fungi;domain;Basidiomycota;phylum;Agaricomycetes;class;Polyporales;order;Sparassidaceae;family;Sparassis;genus
```

## SILVA

```
>GCVF01000431.1.2369 Bacteria;Proteobacteria;Gammaproteobacteria;Oceanospirillales;Alcanivoraceae;Alcanivorax;Thalassiosira rotula
CGUGCACGGUGGAUGCCUUGGCAGCCAGAGGCGAUGAAGGACGUUGUAGCCUGCGAUAAGCUCCGGUUAGGUGGCAAACA
```

## Smithsonian Museum of Natural History: Mammals

```{r}
smith_data <- readr::read_csv("datasets/SNMNH.csv")
```

## GBIF: archea

```{r}
gbif_data <- readr::read_tsv("datasets/gbif_archea.csv")
```


## Atlas of Living Australia

```
```